### ISSUE TITLE
PROD: Error 500 when login with social account from google

### ISSUE THREAD

**Issue by joschkappel** [joschkappel/dunkomatic_next#390]
Get a 500 when loogin in with google account:

`[2022-06-10 06:46:45] prod.INFO: redirecting oauth request to provider {"provider":"google"}
[2022-06-10 06:46:46] prod.ERROR:  {"exception":"[object] (Laravel\\Socialite\\Two\\InvalidStateException(code: 0):  at /var/www/dunkonxt/vendor/laravel/socialite/src/Two/AbstractProvider.php:236)
[stacktrace]
#0 /var/www/dunkonxt/app/Http/Controllers/Auth/SocialAuthController.php(65): Laravel\\Socialite\\Two\\AbstractProvider->user()
#1 /var/www/dunkonxt/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Auth\\SocialAuthController->registerFromOauth(Object(Illuminate\\Http\\Request), 'google')
#2 /var/www/dunkonxt/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('registerFromOau...', Array)
#3 /var/www/dunkonxt/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Auth\\SocialAuthController), 'registerFromOau...')`

**Comment by joschkappel** [comment]
check this out [https://floyk.com/en/post/laravel-socialite-twoinvalidstateexception](https://floyk.com/en/post/laravel-socialite-twoinvalidstateexception)
