### ISSUE TITLE
PROD: errror at teamware file generation

### ISSUE THREAD

**Issue by joschkappel** [joschkappel/dunkomatic_next#490]
`[2022-07-07 00:00:43] prod.INFO: [EXCEL EXPORT] creating LEAGUE GAMES sheet. {"league-id":325}
[2022-07-07 00:00:43] prod.INFO: [JOB][TEAMWARE REPORTS] started. {"league-id":323}
[2022-07-07 00:00:44] prod.INFO: [JOB][TEAMWARE REPORTS] started. {"league-id":325}
[2022-07-07 00:00:44] prod.ERROR: Undefined array key 13 (View: /var/www/dunkonxt/resources/views/reports/teamware_game.blade.php) {"exception":"[object] (Illuminate\\View\\ViewException(code: 0): Undefined array key 13 (View: /var/www/dunkonxt/resources/views/reports/teamware_game.blade.php) at /var/www/dunkonxt/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1679)
[stacktrace]
#0 /var/www/dunkonxt/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(60): Illuminate\\View\\Engines\\CompilerEngine->handleViewException(Object(ErrorException), 0)
#1 /var/www/dunkonxt/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/var/www/dunkon...', Array)
#2 /var/www/dunkonxt/vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\\View\\Engines\\CompilerEngine->get('/var/www/dunkon...', Array)
#3 /var/www/dunkonxt/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#4 /var/www/dunkonxt/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#5 /var/www/dunkonxt/vendor/maatwebsite/excel/src/Sheet.php(442): Illuminate\\View\\View->render()
#6 /var/www/dunkonxt/vendor/maatwebsite/excel/src/Sheet.php(212): Maatwebsite\\Excel\\Sheet->fromView(Object(App\\Exports\\TeamwareGamesExport))
#7 /var/www/dunkonxt/vendor/maatwebsite/excel/src/Writer.php(71): Maatwebsite\\Excel\\Sheet->export(Object(App\\Exports\\TeamwareGamesExport))
#8 /var/www/dunkonxt/vendor/maatwebsite/excel/src/Excel.php(195): Maatwebsite\\Excel\\Writer->export(Object(App\\Exports\\TeamwareGamesExport), 'Csv')
#9 /var/www/dunkonxt/vendor/maatwebsite/excel/src/Excel.php(99): Maatwebsite\\Excel\\Excel->export(Object(App\\Exports\\TeamwareGamesExport), 'exports/2022_23...', 'Csv')
#10 /var/www/dunkonxt/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): Maatwebsite\\Excel\\Excel->store(Object(App\\Exports\\TeamwareGamesExport), 'exports/2022_23...', NULL, 'Csv')
#11 /var/www/dunkonxt/app/Jobs/GenerateTeamwareReport.php(68): Illuminate\\Support\\Facades\\Facade::__callStatic('store', Array)
#12 /var/www/dunkonxt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\GenerateTeamwareReport->handle()`

**Comment by joschkappel** [comment]
`[2022-07-07 00:00:44] prod.INFO: [JOB][LEAGUE GAMES REPORTS] started. {"region-id":5,"league-id":329,"format":"HTML"}
[2022-07-07 00:00:44] prod.INFO: [EXCEL EXPORT] creating LEAGUE GAMES sheet. {"league-id":329}
[2022-07-07 00:00:44] prod.INFO: [EXCEL EXPORT] creating LEAGUE GAMES sheet. {"league-id":329}
[2022-07-07 00:00:45] prod.ERROR: Attempt to read property "region" on null (View: /var/www/dunkonxt/resources/views/reports/teamware_game.blade.php) {"exception":"[object] (Illuminate\\View\\ViewException(code: 0): Attempt to read property \"region\" on null (View: /var/www/dunkonxt/resources/views/reports/teamware_game.blade.php) at /var/www/dunkonxt/storage/framework/views/154536cd123dd1dc0d7822ea43076246560ea6cd.php:11)
[stacktrace]
#0 /var/www/dunkonxt/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(60): Illuminate\\View\\Engines\\CompilerEngine->handleViewException(Object(ErrorException), 0)
#1 /var/www/dunkonxt/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/var/www/dunkon...', Array)
#2 /var/www/dunkonxt/vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\\View\\Engines\\CompilerEngine->get('/var/www/dunkon...', Array)
#3 /var/www/dunkonxt/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#4 /var/www/dunkonxt/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#5 /var/www/dunkonxt/vendor/maatwebsite/excel/src/Sheet.php(442): Illuminate\\View\\View->render()
#6 /var/www/dunkonxt/vendor/maatwebsite/excel/src/Sheet.php(212): Maatwebsite\\Excel\\Sheet->fromView(Object(App\\Exports\\TeamwareGamesExport))`
